"""rev

Revision ID: bd6282524acd
Revises: 8cc0553b0274
Create Date: 2024-08-03 00:05:47.198892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd6282524acd'
down_revision: Union[str, None] = '8cc0553b0274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hadith', 'created_at')
    op.drop_column('hadith', 'created_by')
    op.drop_column('hadith', 'updated_at')
    op.drop_column('hadith', 'updated_by')
    op.drop_column('hadith_assesment', 'created_at')
    op.drop_column('hadith_assesment', 'created_by')
    op.drop_column('hadith_assesment', 'updated_at')
    op.drop_column('hadith_assesment', 'updated_by')
    op.drop_column('role', 'created_at')
    op.drop_column('role', 'created_by')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'updated_by')
    op.drop_column('type_hadith', 'created_at')
    op.drop_column('type_hadith', 'created_by')
    op.drop_column('type_hadith', 'updated_at')
    op.drop_column('type_hadith', 'updated_by')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('type_hadith', sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('type_hadith', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('type_hadith', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('type_hadith', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('role', sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('role', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('hadith_assesment', sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hadith_assesment', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('hadith_assesment', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hadith_assesment', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('hadith', sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hadith', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('hadith', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hadith', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###
